name: Publish image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push to GitHub Container Registry
        run: |
          docker login -u luis-herasme -p ${{ secrets.TOKEN }} ghcr.io
          docker build . -t ghcr.io/luis-herasme/signaling-server:latest
          docker push ghcr.io/luis-herasme/signaling-server:latest
